rireki/config/routes.rb
Rireki::Application.routes.draw do

  resources :resumes

  devise_for :users

  devise_scope :user do
    get "sign_in",  to: "devise/sessions#new"
    get "signin",   to: "devise/sessions#new"
    get "log_in",   to: "devise/sessions#new"
    get "login",    to: "devise/sessions#new"

    get "sign_out", to: "devise/sessions#destroy"
    get "signout",  to: "devise/sessions#destroy"
    get "log_out",  to: "devise/sessions#destroy"
    get "logout",   to: "devise/sessions#destroy"
  end

  resources :qualifications

  resources :activities

  resources :educations

  resources :experiences

  get   "dashboard",
        to: "static#dashboard",
        as: "dashboard"

  root "static#landing"

end

rireki/app/models/resume.rb
class Resume < ActiveRecord::Base

  belongs_to  :user

  has_many  :resume_experiences
  has_many  :experiences,     through: :resume_experiences

  has_many  :resume_educations
  has_many  :educations,      through: :resume_educations

  has_many  :resume_activities
  has_many  :activities,      through: :resume_activities

  has_many  :resume_qualifications
  has_many  :qualifications,  through: :resume_qualifications

  validates_presence_of :name

end

rireki/app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  before_action :set_resume, only: [:show, :edit, :update, :destroy]

  def index
    @resumes = current_user.resumes.all
  end

  def show
  end

  def new
    @resume = Resume.new
    set_resume_entries
  end

  def edit
    set_resume_entries
  end

  def create
    @resume = current_user.resumes.build(resume_params)
    @resume.save

    redirect_to resume_path(@resume)
  end

  def update
    @resume.update(resume_params)

    redirect_to resume_path(@resume)
  end

  def destroy
    @resume.destroy
  end

  private
    def set_resume
      @resume = Resume.find(params[:id])
      ownership_check!(@resume)
    end

    def set_resume_entries
      @experiences    = current_user.experiences.all
      @educations     = current_user.educations.all
      @activities     = current_user.activities.all
      @qualifications = current_user.qualifications.all
    end

    def resume_params
      params.require(:resume).permit(:name, :objective,
        experience_ids: [], activity_ids: [], education_ids: [], qualification_ids: [])
    end
end

rireki/app/helpers/resumes_helper.rb
module ResumesHelper
end

rireki/app/views/resumes/_form.html.erb
<%= form_for(@resume) do |f| %>
  <% if @resume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resume.errors.count, "error") %> prohibited this resume from being saved:</h2>

      <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :objective %><br>
    <%= f.text_area :objective %>
  </div>

  <!-- Where the action happens -->
  <%= render  layout:  "form_association_checkboxes",
              locals:   { f: f, resume: @resume,
                collection: @experiences,
                association_name: 'experiences' } do |exp| %>
    <%= exp.title %>
  <% end -%>

  <%= render  layout:  "form_association_checkboxes",
              locals:   { f: f, resume: @resume,
                collection: @educations,
                association_name: 'educations' } do |edu| %>
    <%= edu.award %>
  <% end -%>

  <%= f.label :activities %>
  <% @activities.each do |act| %>
    <div>
      <%= label_tag "activity_#{act.id}" do %>
        <%= check_box_tag :activity_ids, act.id, @resume.activities.include?(act),
            name: "resume[activity_ids][]", id: "activity_#{act.id}" %>
        <%= act.title %>
      <% end -%>
    </div>
  <% end %>

  <%= render  layout:  "form_association_checkboxes",
              locals:   { f: f, resume: @resume,
                collection: @qualifications,
                association_name: 'qualifications' } do |edu| %>
    <%= edu.description %>
  <% end -%>


  <!-- End "the action" -->


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rireki/app/views/resumes/_form_association_checkboxes.html.erb
<%# Get a helpful string for naming fields.  %>
<% singular_name = association_name.singularize %>

<%= f.label association_name %>

<% collection.each do |entry| %>
  <%
    # The id used for labels & the checkbox itself.
    field_id    = "#{singular_name}_#{entry.id}"
    # Field name for Rails to interpret this as an array-style parameter
    field_name  = "resume[#{singular_name}_ids][]"
  %>
  <div>
    <%= label_tag field_id do %>
      <%# Hidden tag with empty value, which is shadowed when box is checked. %>
      <%= hidden_field_tag "#{field_id}_removed", "", name: field_name %>

      <%# Checkbox whose value is the entry's id %>
      <%= check_box_tag "#{singular_name}_ids", entry.id,
            @resume.send(association_name).include?(entry),
            name: field_name, id: field_id %>

      <%# Allow the calling view to provide the text next to the box. %>
      <%= yield entry %>

    <% end -%>
  </div>
<% end %>

rireki/app/views/resumes/edit.html.erb
<h1>Editing resume</h1>

<%= render 'form' %>

<%= link_to 'Show', @resume %> |
<%= link_to 'Back', resumes_path %>

rireki/app/views/resumes/index.html.erb
<h1>Listing resumes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Objective</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.name %></td>
        <td><%= resume.objective %></td>
        <td><%= link_to 'Show', resume %></td>
        <td><%= link_to 'Edit', edit_resume_path(resume) %></td>
        <td><%= link_to 'Destroy', resume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resume', new_resume_path %>

rireki/app/views/resumes/new.html.erb
<h1>New resume</h1>

<%= render 'form' %>

<%= link_to 'Back', resumes_path %>

rireki/app/views/resumes/show.html.erb
<h1><%= @resume.user.name %></h1>

<% if @resume.objective.present? %>
  <h3>Objective</h3>
  <%= @resume.objective %>
<% end -%>

<% @resume.experiences.each do |exp| %>
  <div>
    <%= exp.title %> | <%= exp.company %> | <%= exp.date %>
  </div>
<% end -%>

<% @resume.educations.each do |edu| %>
  <div>
    <%= edu.award %> | <%= edu.school %> | <%= edu.date %>
  </div>
<% end -%>

<% @resume.activities.each do |act| %>
  <div>
    <%= act.title %>
  </div>
<% end -%>

<% @resume.qualifications.each do |qual| %>
  <div>
    <%= qual.description %>
  </div>
<% end -%>