rireki/config/routes.rb
Rireki::Application.routes.draw do

  resources :resumes

  devise_for :users

  devise_scope :user do
    get "sign_in",  to: "devise/sessions#new"
    get "signin",   to: "devise/sessions#new"
    get "log_in",   to: "devise/sessions#new"
    get "login",    to: "devise/sessions#new"

    get "sign_out", to: "devise/sessions#destroy"
    get "signout",  to: "devise/sessions#destroy"
    get "log_out",  to: "devise/sessions#destroy"
    get "logout",   to: "devise/sessions#destroy"
  end

  resources :qualifications

  resources :activities

  resources :educations

  resources :experiences

  get   "dashboard",
        to: "static#dashboard",
        as: "dashboard"

  root "static#landing"

end

rireki/app/models/activity.rb
class Activity < ActiveRecord::Base

  belongs_to :user
  validates_presence_of :date, :title, :description, :user

end

rireki/app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = current_user.activities.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = current_user.activities.build(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @activity }
      else
        format.html { render action: 'new' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
      ownership_check!(@activity)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:date, :title, :description)
    end
end

rireki/app/helpers/activities_helper.rb
module ActivitiesHelper
end

rireki/app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rireki/app/views/activities/_list.html.erb
<h1>Listing activities</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% activities.each do |activity| %>
      <tr>
        <td><%= activity.date %></td>
        <td><%= activity.title %></td>
        <td><%= activity.description %></td>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

rireki/app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

rireki/app/views/activities/index.html.erb
<%= render partial: 'list', locals: { activities: @activities } %>

rireki/app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

rireki/app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @activity.date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @activity.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @activity.description %>
</p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>