rireki/config/routes.rb
Rireki::Application.routes.draw do

  resources :resumes

  devise_for :users

  devise_scope :user do
    get "sign_in",  to: "devise/sessions#new"
    get "signin",   to: "devise/sessions#new"
    get "log_in",   to: "devise/sessions#new"
    get "login",    to: "devise/sessions#new"

    get "sign_out", to: "devise/sessions#destroy"
    get "signout",  to: "devise/sessions#destroy"
    get "log_out",  to: "devise/sessions#destroy"
    get "logout",   to: "devise/sessions#destroy"
  end

  resources :qualifications

  resources :activities

  resources :educations

  resources :experiences

  get   "dashboard",
        to: "static#dashboard",
        as: "dashboard"

  root "static#landing"

end

rireki/app/models/experience.rb
class Experience < ActiveRecord::Base

  belongs_to :user
  validates_presence_of :date, :title, :description, :company, :user

end

rireki/app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  # GET /experiences
  # GET /experiences.json
  def index
    @experiences = current_user.experiences.all
  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences
  # POST /experiences.json
  def create
    @experience = current_user.experiences.build(experience_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'Experience was successfully created.' }
        format.json { render action: 'show', status: :created, location: @experience }
      else
        format.html { render action: 'new' }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1
  # PATCH/PUT /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to @experience, notice: 'Experience was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    @experience.destroy
    respond_to do |format|
      format.html { redirect_to experiences_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
      ownership_check!(@experience)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experience_params
      params.require(:experience).permit(:date, :title, :description, :company)
    end
end

rireki/app/helpers/experiences_helper.rb
module ExperiencesHelper
end

rireki/app/views/experiences/_form.html.erb
<%= form_for(@experience) do |f| %>
  <% if @experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% @experience.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rireki/app/views/experiences/_list.html.erb
<h1>Listing experiences</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Title</th>
      <th>Description</th>
      <th>Company</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @experiences.each do |experience| %>
      <tr>
        <td><%= experience.date %></td>
        <td><%= experience.title %></td>
        <td><%= experience.description %></td>
        <td><%= experience.company %></td>
        <td><%= link_to 'Show', experience %></td>
        <td><%= link_to 'Edit', edit_experience_path(experience) %></td>
        <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experience', new_experience_path %>

rireki/app/views/experiences/edit.html.erb
<h1>Editing experience</h1>

<%= render 'form' %>

<%= link_to 'Show', @experience %> |
<%= link_to 'Back', experiences_path %>

rireki/app/views/experiences/index.html.erb
<%= render partial: 'list' %>

rireki/app/views/experiences/new.html.erb
<h1>New experience</h1>

<%= render 'form' %>

<%= link_to 'Back', experiences_path %>

rireki/app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @experience.date %>
</p>

<p>
  <strong>Title:</strong>
  <%= @experience.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @experience.description %>
</p>

<p>
  <strong>Company:</strong>
  <%= @experience.company %>
</p>

<%= link_to 'Edit', edit_experience_path(@experience) %> |
<%= link_to 'Back', experiences_path %>