rireki/config/routes.rb
Rireki::Application.routes.draw do

  resources :resumes

  devise_for :users

  devise_scope :user do
    get "sign_in",  to: "devise/sessions#new"
    get "signin",   to: "devise/sessions#new"
    get "log_in",   to: "devise/sessions#new"
    get "login",    to: "devise/sessions#new"

    get "sign_out", to: "devise/sessions#destroy"
    get "signout",  to: "devise/sessions#destroy"
    get "log_out",  to: "devise/sessions#destroy"
    get "logout",   to: "devise/sessions#destroy"
  end

  resources :qualifications

  resources :activities

  resources :educations

  resources :experiences

  get   "dashboard",
        to: "static#dashboard",
        as: "dashboard"

  root "static#landing"

end

rireki/app/models/education.rb
class Education < ActiveRecord::Base

  belongs_to :user
  validates_presence_of :date, :award, :description, :school, :location, :user

end

rireki/app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :set_education, only: [:show, :edit, :update, :destroy]

  # GET /educations
  # GET /educations.json
  def index
    # @educations = Education.where(user: current_user).all
    # @educations = Education.where(user_id: current_user.id).all
    @educations = current_user.educations.to_a
  end

  # GET /educations/1
  # GET /educations/1.json
  def show
  end

  # GET /educations/new
  def new
    @education = Education.new
  end

  # GET /educations/1/edit
  def edit
  end

  # POST /educations
  # POST /educations.json
  def create
    @education = current_user.educations.build(education_params)

    respond_to do |format|
      if @education.save
        format.html { redirect_to @education, notice: 'Education was successfully created.' }
        format.json { render action: 'show', status: :created, location: @education }
      else
        format.html { render action: 'new' }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /educations/1
  # PATCH/PUT /educations/1.json
  def update
    respond_to do |format|
      if @education.update(education_params)
        format.html { redirect_to @education, notice: 'Education was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @education.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /educations/1
  # DELETE /educations/1.json
  def destroy
    @education.destroy
    respond_to do |format|
      format.html { redirect_to educations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education
      @education = Education.find(params[:id])
      ownership_check!(@education)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_params
      params.require(:education).permit(:date, :award, :description, :school, :location)
    end
end

rireki/app/helpers/educations_helper.rb
module EducationsHelper
end

rireki/app/views/educations/_form.html.erb
<%= form_for(@education) do |f| %>
  <% if @education.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@education.errors.count, "error") %> prohibited this education from being saved:</h2>

      <ul>
      <% @education.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :award %><br>
    <%= f.text_field :award %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :school %><br>
    <%= f.text_field :school %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rireki/app/views/educations/_list.html.erb
<h1>Listing educations</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Award</th>
      <th>Description</th>
      <th>School</th>
      <th>Location</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @educations.each do |education| %>
      <tr>
        <td><%= education.date %></td>
        <td><%= education.award %></td>
        <td><%= education.description %></td>
        <td><%= education.school %></td>
        <td><%= education.location %></td>
        <td><%= link_to 'Show', education %></td>
        <td><%= link_to 'Edit', edit_education_path(education) %></td>
        <td><%= link_to 'Destroy', education, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Education', new_education_path %>

rireki/app/views/educations/edit.html.erb
<h1>Editing education</h1>

<%= render 'form' %>

<%= link_to 'Show', @education %> |
<%= link_to 'Back', educations_path %>

rireki/app/views/educations/index.html.erb
<%= render partial: "list" %>

rireki/app/views/educations/new.html.erb
<h1>New education</h1>

<%= render 'form' %>

<%= link_to 'Back', educations_path %>

rireki/app/views/educations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @education.date %>
</p>

<p>
  <strong>Award:</strong>
  <%= @education.award %>
</p>

<p>
  <strong>Description:</strong>
  <%= @education.description %>
</p>

<p>
  <strong>School:</strong>
  <%= @education.school %>
</p>

<p>
  <strong>Location:</strong>
  <%= @education.location %>
</p>

<%= link_to 'Edit', edit_education_path(@education) %> |
<%= link_to 'Back', educations_path %>